server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Admin Service - Endpoints admin
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**

        # Admin Service - Endpoints contact public
        - id: admin-service-contact
          uri: lb://admin-service
          predicates:
            - Path=/api/contact/**

        # Product Service
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1

        # Frontend Service
        - id: frontend
          uri: http://localhost:3000
          predicates:
            - Path=/**

        # Eureka Server
        - id: eureka-server
          uri: lb://eureka-server
          predicates:
            - Path=/eureka/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true

# Configuration Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Configuration de sécurité
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Logs de debug
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG 